import {
  Activity,
  Binary,
  Boxes,
  ChartBar,
  Container,
  Database,
  Gauge,
  Globe,
  HardDrive,
  Layers,
  MessageSquare,
  Network,
  Package,
  Radio,
  Route,
  Rows3,
  Satellite,
  Scale,
  Server,
  Waypoints,
  Zap,
} from "lucide-react";
import type { CatalogItem, Category, MetricProfile } from "./types";

/**
 * Catálogo de componentes do protótipo (PRD §10).
 * Todos os dados são mockados — não há registry real antes do Milestone 1 (PRD §70).
 */

const cpuMetrics = (cpuCoef: number, extra: MetricProfile[] = []): MetricProfile[] => [
  { key: "cpu", label: "CPU", unit: "%", coef: cpuCoef },
  ...extra,
];

export const CATALOG: CatalogItem[] = [
  // ---------------------------------------------------------------- Compute
  {
    type: "aws.ec2",
    monthlyCostUsd: 60,
    name: "EC2",
    title: "EC2 Instance",
    category: "compute",
    provider: "aws",
    icon: Server,
    defaults: { instanceType: "t3.medium", instances: 2, autoScaling: false },
    properties: [
      { key: "instanceType", label: "Instance type", kind: "select", options: ["t3.small", "t3.medium", "t3.large", "m6i.large", "c6i.xlarge"] },
      { key: "instances", label: "Instances", kind: "number", min: 1, max: 50 },
      { key: "autoScaling", label: "Auto Scaling", kind: "switch" },
    ],
    summaryKeys: ["instances", "instanceType"],
    capacityRps: 2200,
    metrics: cpuMetrics(88, [{ key: "memory", label: "Memory", unit: "%", coef: 74 }]),
  },
  {
    type: "aws.ecs",
    monthlyCostUsd: 120,
    name: "ECS",
    title: "ECS Service",
    category: "compute",
    provider: "aws",
    icon: Container,
    defaults: {
      cpu: "2 vCPU",
      memory: "4GB",
      desiredReplicas: 2,
      minReplicas: 2,
      maxReplicas: 10,
      autoScaling: true,
    },
    properties: [
      { key: "cpu", label: "CPU", kind: "select", options: ["0.5 vCPU", "1 vCPU", "2 vCPU", "4 vCPU"] },
      { key: "memory", label: "Memory", kind: "select", options: ["1GB", "2GB", "4GB", "8GB", "16GB"] },
      { key: "desiredReplicas", label: "Desired replicas", kind: "number", min: 1, max: 50 },
      { key: "minReplicas", label: "Minimum replicas", kind: "number", min: 1, max: 50 },
      { key: "maxReplicas", label: "Maximum replicas", kind: "number", min: 1, max: 100 },
      { key: "autoScaling", label: "Auto Scaling", kind: "switch" },
    ],
    summaryKeys: ["desiredReplicas", "cpu", "memory"],
    capacityRps: 3300,
    metrics: cpuMetrics(66, [{ key: "memory", label: "Memory", unit: "%", coef: 58 }]),
  },
  {
    type: "aws.lambda",
    monthlyCostUsd: 18,
    name: "Lambda",
    title: "Lambda Function",
    category: "compute",
    provider: "aws",
    icon: Zap,
    defaults: { memoryMb: 512, timeoutMs: 30000, concurrency: 100 },
    properties: [
      { key: "memoryMb", label: "Memory", kind: "number", unit: "MB", min: 128, max: 10240, step: 128 },
      { key: "timeoutMs", label: "Timeout", kind: "number", unit: "ms", min: 1000, max: 900000, step: 1000 },
      { key: "concurrency", label: "Reserved concurrency", kind: "number", min: 1, max: 1000 },
    ],
    summaryKeys: ["memoryMb", "concurrency"],
    capacityRps: 5000,
    metrics: cpuMetrics(60, [{ key: "throttles", label: "Throttles", unit: "%", coef: 42 }]),
  },
  {
    type: "opensource.docker",
    monthlyCostUsd: 15,
    name: "Docker",
    title: "Docker Container",
    category: "compute",
    provider: "opensource",
    icon: Boxes,
    defaults: { image: "app:latest", cpu: "1 vCPU", memory: "2GB", replicas: 1 },
    properties: [
      { key: "image", label: "Image", kind: "text", placeholder: "app:latest" },
      { key: "cpu", label: "CPU", kind: "select", options: ["0.5 vCPU", "1 vCPU", "2 vCPU", "4 vCPU"] },
      { key: "memory", label: "Memory", kind: "select", options: ["512MB", "1GB", "2GB", "4GB"] },
      { key: "replicas", label: "Replicas", kind: "number", min: 1, max: 20 },
    ],
    summaryKeys: ["replicas", "cpu", "memory"],
    capacityRps: 1500,
    metrics: cpuMetrics(90, [{ key: "memory", label: "Memory", unit: "%", coef: 80 }]),
  },
  {
    type: "opensource.kubernetes",
    monthlyCostUsd: 140,
    name: "Kubernetes",
    title: "Kubernetes Deployment",
    category: "compute",
    provider: "opensource",
    icon: Layers,
    defaults: { replicas: 3, cpu: "2 vCPU", memory: "4GB", hpa: true },
    properties: [
      { key: "replicas", label: "Replicas", kind: "number", min: 1, max: 100 },
      { key: "cpu", label: "CPU request", kind: "select", options: ["0.5 vCPU", "1 vCPU", "2 vCPU", "4 vCPU"] },
      { key: "memory", label: "Memory request", kind: "select", options: ["1GB", "2GB", "4GB", "8GB"] },
      { key: "hpa", label: "Horizontal Pod Autoscaler", kind: "switch" },
    ],
    summaryKeys: ["replicas", "cpu", "memory"],
    capacityRps: 6000,
    metrics: cpuMetrics(62, [{ key: "memory", label: "Memory", unit: "%", coef: 55 }]),
  },

  // ---------------------------------------------------------------- Storage
  {
    type: "aws.s3",
    monthlyCostUsd: 12,
    name: "S3",
    title: "S3 Bucket",
    category: "storage",
    provider: "aws",
    icon: HardDrive,
    defaults: { storageClass: "Standard", versioning: true, encryption: "SSE-S3" },
    properties: [
      { key: "storageClass", label: "Storage class", kind: "select", options: ["Standard", "Intelligent-Tiering", "Standard-IA", "Glacier"] },
      { key: "versioning", label: "Versioning", kind: "switch" },
      { key: "encryption", label: "Encryption", kind: "select", options: ["SSE-S3", "SSE-KMS", "None"] },
    ],
    summaryKeys: ["storageClass"],
    capacityRps: 30000,
    metrics: [{ key: "latency", label: "Latency", unit: "ms", coef: 34 }],
    alternative: "opensource.minio",
  },
  {
    type: "opensource.minio",
    monthlyCostUsd: 45,
    name: "MinIO",
    title: "MinIO Object Storage",
    category: "storage",
    provider: "opensource",
    icon: Package,
    defaults: { nodes: 4, diskGb: 500, erasureCoding: true },
    properties: [
      { key: "nodes", label: "Nodes", kind: "number", min: 1, max: 32 },
      { key: "diskGb", label: "Disk per node", kind: "number", unit: "GB", min: 20, max: 10000, step: 10 },
      { key: "erasureCoding", label: "Erasure coding", kind: "switch" },
    ],
    summaryKeys: ["nodes", "diskGb"],
    capacityRps: 9000,
    metrics: cpuMetrics(70, [{ key: "latency", label: "Latency", unit: "ms", coef: 60 }]),
    alternative: "aws.s3",
  },

  // --------------------------------------------------------------- Database
  {
    type: "aws.rds",
    monthlyCostUsd: 160,
    name: "RDS",
    title: "RDS PostgreSQL",
    category: "database",
    provider: "aws",
    icon: Database,
    defaults: {
      engine: "PostgreSQL 16",
      instanceClass: "db.t3.medium",
      storageGb: 100,
      multiAz: false,
      maxConnections: 200,
    },
    properties: [
      { key: "engine", label: "Engine", kind: "select", options: ["PostgreSQL 16", "PostgreSQL 15", "MySQL 8", "MariaDB 11"] },
      { key: "instanceClass", label: "Instance", kind: "select", options: ["db.t3.small", "db.t3.medium", "db.m6g.large", "db.m6g.xlarge", "db.r6g.xlarge"] },
      { key: "storageGb", label: "Storage", kind: "number", unit: "GB", min: 20, max: 16000, step: 10 },
      { key: "multiAz", label: "Multi-AZ", kind: "switch" },
      { key: "maxConnections", label: "Max connections", kind: "number", min: 20, max: 5000, step: 10 },
    ],
    summaryKeys: ["instanceClass", "storageGb"],
    capacityRps: 2600,
    metrics: cpuMetrics(83.5, [
      { key: "connections", label: "Connections", unit: "%", coef: 79 },
      { key: "latency", label: "Latency", unit: "ms", coef: 269 },
    ]),
  },
  {
    type: "opensource.postgresql",
    monthlyCostUsd: 90,
    name: "PostgreSQL",
    title: "PostgreSQL",
    category: "database",
    provider: "opensource",
    icon: Database,
    defaults: { version: "16", cpu: "2 vCPU", memory: "8GB", maxConnections: 200, replication: false },
    properties: [
      { key: "version", label: "Version", kind: "select", options: ["14", "15", "16", "17"] },
      { key: "cpu", label: "CPU", kind: "select", options: ["1 vCPU", "2 vCPU", "4 vCPU", "8 vCPU"] },
      { key: "memory", label: "Memory", kind: "select", options: ["2GB", "4GB", "8GB", "16GB", "32GB"] },
      { key: "maxConnections", label: "Max connections", kind: "number", min: 20, max: 5000, step: 10 },
      { key: "replication", label: "Streaming replication", kind: "switch" },
    ],
    summaryKeys: ["version", "cpu", "memory"],
    capacityRps: 2400,
    metrics: cpuMetrics(85, [
      { key: "connections", label: "Connections", unit: "%", coef: 80 },
      { key: "latency", label: "Latency", unit: "ms", coef: 280 },
    ]),
    alternative: "aws.rds",
  },
  {
    type: "opensource.mysql",
    monthlyCostUsd: 85,
    name: "MySQL",
    title: "MySQL",
    category: "database",
    provider: "opensource",
    icon: Database,
    defaults: { version: "8.4", cpu: "2 vCPU", memory: "8GB", maxConnections: 300 },
    properties: [
      { key: "version", label: "Version", kind: "select", options: ["8.0", "8.4"] },
      { key: "cpu", label: "CPU", kind: "select", options: ["1 vCPU", "2 vCPU", "4 vCPU", "8 vCPU"] },
      { key: "memory", label: "Memory", kind: "select", options: ["2GB", "4GB", "8GB", "16GB"] },
      { key: "maxConnections", label: "Max connections", kind: "number", min: 20, max: 5000, step: 10 },
    ],
    summaryKeys: ["version", "cpu", "memory"],
    capacityRps: 2300,
    metrics: cpuMetrics(86, [{ key: "connections", label: "Connections", unit: "%", coef: 82 }]),
  },

  // ------------------------------------------------------------------ Cache
  {
    type: "opensource.redis",
    monthlyCostUsd: 70,
    name: "Redis",
    title: "Redis",
    category: "cache",
    provider: "opensource",
    icon: Zap,
    defaults: { version: "7.4", memory: "2GB", evictionPolicy: "allkeys-lru", persistence: false },
    properties: [
      { key: "version", label: "Version", kind: "select", options: ["6.2", "7.2", "7.4"] },
      { key: "memory", label: "Memory", kind: "select", options: ["512MB", "1GB", "2GB", "4GB", "8GB"] },
      { key: "evictionPolicy", label: "Eviction policy", kind: "select", options: ["noeviction", "allkeys-lru", "volatile-lru", "allkeys-lfu"] },
      { key: "persistence", label: "Persistence", kind: "switch" },
    ],
    summaryKeys: ["version", "memory"],
    capacityRps: 15000,
    metrics: cpuMetrics(55, [{ key: "memory", label: "Memory", unit: "%", coef: 64 }]),
    alternative: "aws.elasticache",
  },
  {
    type: "aws.elasticache",
    monthlyCostUsd: 85,
    name: "ElastiCache",
    title: "ElastiCache Redis",
    category: "cache",
    provider: "aws",
    icon: Zap,
    defaults: { nodeType: "cache.t3.micro", nodes: 1, multiAz: false },
    properties: [
      { key: "nodeType", label: "Node type", kind: "select", options: ["cache.t3.micro", "cache.t3.small", "cache.m6g.large", "cache.r6g.large"] },
      { key: "nodes", label: "Nodes", kind: "number", min: 1, max: 20 },
      { key: "multiAz", label: "Multi-AZ", kind: "switch" },
    ],
    summaryKeys: ["nodes", "nodeType"],
    capacityRps: 18000,
    metrics: cpuMetrics(52, [{ key: "memory", label: "Memory", unit: "%", coef: 60 }]),
    alternative: "opensource.redis",
  },

  // ---------------------------------------------------------------- Network
  {
    type: "aws.alb",
    monthlyCostUsd: 22,
    name: "ALB",
    title: "Application Load Balancer",
    category: "network",
    provider: "aws",
    icon: Scale,
    defaults: { scheme: "internet-facing", listeners: "HTTPS:443", idleTimeoutS: 60, stickySessions: false },
    properties: [
      { key: "scheme", label: "Scheme", kind: "select", options: ["internet-facing", "internal"] },
      { key: "listeners", label: "Listeners", kind: "text", placeholder: "HTTPS:443" },
      { key: "idleTimeoutS", label: "Idle timeout", kind: "number", unit: "s", min: 1, max: 4000 },
      { key: "stickySessions", label: "Sticky sessions", kind: "switch" },
    ],
    summaryKeys: ["scheme", "listeners"],
    capacityRps: 20000,
    metrics: [
      { key: "connections", label: "Connections", unit: "%", coef: 48 },
      { key: "latency", label: "Latency", unit: "ms", coef: 18 },
    ],
  },
  {
    type: "aws.nlb",
    monthlyCostUsd: 20,
    name: "NLB",
    title: "Network Load Balancer",
    category: "network",
    provider: "aws",
    icon: Network,
    defaults: { scheme: "internet-facing", listeners: "TCP:443", crossZone: true },
    properties: [
      { key: "scheme", label: "Scheme", kind: "select", options: ["internet-facing", "internal"] },
      { key: "listeners", label: "Listeners", kind: "text", placeholder: "TCP:443" },
      { key: "crossZone", label: "Cross-zone balancing", kind: "switch" },
    ],
    summaryKeys: ["scheme", "listeners"],
    capacityRps: 40000,
    metrics: [{ key: "connections", label: "Connections", unit: "%", coef: 40 }],
  },
  {
    type: "aws.cloudfront",
    monthlyCostUsd: 34,
    name: "CloudFront",
    title: "CloudFront Distribution",
    category: "network",
    provider: "aws",
    icon: Globe,
    defaults: { priceClass: "PriceClass_100", cachePolicy: "CachingOptimized", compress: true },
    properties: [
      { key: "priceClass", label: "Price class", kind: "select", options: ["PriceClass_100", "PriceClass_200", "PriceClass_All"] },
      { key: "cachePolicy", label: "Cache policy", kind: "select", options: ["CachingOptimized", "CachingDisabled", "Custom"] },
      { key: "compress", label: "Compression", kind: "switch" },
    ],
    summaryKeys: ["cachePolicy"],
    capacityRps: 50000,
    metrics: [
      { key: "cacheHit", label: "Cache hit", unit: "%", coef: 72 },
      { key: "latency", label: "Latency", unit: "ms", coef: 12 },
    ],
  },
  {
    type: "opensource.traefik",
    monthlyCostUsd: 15,
    name: "Traefik",
    title: "Traefik Proxy",
    category: "network",
    provider: "opensource",
    icon: Waypoints,
    defaults: { entrypoints: "web, websecure", tls: true, replicas: 2 },
    properties: [
      { key: "entrypoints", label: "Entrypoints", kind: "text", placeholder: "web, websecure" },
      { key: "tls", label: "TLS", kind: "switch" },
      { key: "replicas", label: "Replicas", kind: "number", min: 1, max: 20 },
    ],
    summaryKeys: ["replicas", "entrypoints"],
    capacityRps: 12000,
    metrics: cpuMetrics(58, [{ key: "connections", label: "Connections", unit: "%", coef: 52 }]),
  },
  {
    type: "opensource.nginx",
    monthlyCostUsd: 12,
    name: "Nginx",
    title: "Nginx",
    category: "network",
    provider: "opensource",
    icon: Route,
    defaults: { workerProcesses: "auto", replicas: 2, gzip: true },
    properties: [
      { key: "workerProcesses", label: "Worker processes", kind: "select", options: ["auto", "1", "2", "4", "8"] },
      { key: "replicas", label: "Replicas", kind: "number", min: 1, max: 20 },
      { key: "gzip", label: "gzip", kind: "switch" },
    ],
    summaryKeys: ["replicas", "workerProcesses"],
    capacityRps: 14000,
    metrics: cpuMetrics(56, [{ key: "connections", label: "Connections", unit: "%", coef: 50 }]),
  },

  // -------------------------------------------------------------- Messaging
  {
    type: "aws.sqs",
    monthlyCostUsd: 8,
    name: "SQS",
    title: "SQS Queue",
    category: "queue",
    provider: "aws",
    icon: MessageSquare,
    defaults: { queueType: "Standard", visibilityTimeoutS: 30, dlq: true },
    properties: [
      { key: "queueType", label: "Queue type", kind: "select", options: ["Standard", "FIFO"] },
      { key: "visibilityTimeoutS", label: "Visibility timeout", kind: "number", unit: "s", min: 0, max: 43200 },
      { key: "dlq", label: "Dead-letter queue", kind: "switch" },
    ],
    summaryKeys: ["queueType"],
    capacityRps: 25000,
    metrics: [{ key: "queueDepth", label: "Queue depth", unit: "%", coef: 64 }],
    alternative: "opensource.rabbitmq",
  },
  {
    type: "opensource.rabbitmq",
    monthlyCostUsd: 35,
    name: "RabbitMQ",
    title: "RabbitMQ",
    category: "queue",
    provider: "opensource",
    icon: Rows3,
    defaults: { nodes: 3, durable: true, prefetch: 100 },
    properties: [
      { key: "nodes", label: "Nodes", kind: "number", min: 1, max: 12 },
      { key: "durable", label: "Durable queues", kind: "switch" },
      { key: "prefetch", label: "Prefetch", kind: "number", min: 1, max: 5000 },
    ],
    summaryKeys: ["nodes", "prefetch"],
    capacityRps: 9000,
    metrics: cpuMetrics(66, [{ key: "queueDepth", label: "Queue depth", unit: "%", coef: 70 }]),
    alternative: "aws.sqs",
  },
  {
    type: "opensource.nats",
    monthlyCostUsd: 20,
    name: "NATS",
    title: "NATS",
    category: "queue",
    provider: "opensource",
    icon: Radio,
    defaults: { cluster: 3, jetstream: true },
    properties: [
      { key: "cluster", label: "Cluster size", kind: "number", min: 1, max: 12 },
      { key: "jetstream", label: "JetStream", kind: "switch" },
    ],
    summaryKeys: ["cluster"],
    capacityRps: 40000,
    metrics: cpuMetrics(48, [{ key: "queueDepth", label: "Queue depth", unit: "%", coef: 44 }]),
  },
  {
    type: "opensource.kafka",
    monthlyCostUsd: 150,
    name: "Kafka",
    title: "Apache Kafka",
    category: "queue",
    provider: "opensource",
    icon: Binary,
    defaults: { brokers: 3, partitions: 12, replicationFactor: 3 },
    properties: [
      { key: "brokers", label: "Brokers", kind: "number", min: 1, max: 30 },
      { key: "partitions", label: "Partitions", kind: "number", min: 1, max: 500 },
      { key: "replicationFactor", label: "Replication factor", kind: "number", min: 1, max: 5 },
    ],
    summaryKeys: ["brokers", "partitions"],
    capacityRps: 60000,
    metrics: cpuMetrics(50, [{ key: "queueDepth", label: "Consumer lag", unit: "%", coef: 46 }]),
  },

  // ---------------------------------------------------------- Observability
  {
    type: "opensource.prometheus",
    monthlyCostUsd: 30,
    name: "Prometheus",
    title: "Prometheus",
    category: "observability",
    provider: "opensource",
    icon: Activity,
    defaults: { retentionDays: 15, scrapeIntervalS: 15, storageGb: 100 },
    properties: [
      { key: "retentionDays", label: "Retention", kind: "number", unit: "days", min: 1, max: 365 },
      { key: "scrapeIntervalS", label: "Scrape interval", kind: "number", unit: "s", min: 5, max: 300, step: 5 },
      { key: "storageGb", label: "Storage", kind: "number", unit: "GB", min: 10, max: 5000, step: 10 },
    ],
    summaryKeys: ["retentionDays", "scrapeIntervalS"],
    capacityRps: 20000,
    metrics: cpuMetrics(44, [{ key: "memory", label: "Memory", unit: "%", coef: 50 }]),
  },
  {
    type: "opensource.grafana",
    monthlyCostUsd: 20,
    name: "Grafana",
    title: "Grafana",
    category: "observability",
    provider: "opensource",
    icon: ChartBar,
    defaults: { version: "11", authProvider: "OAuth", dashboards: 12 },
    properties: [
      { key: "version", label: "Version", kind: "select", options: ["10", "11", "12"] },
      { key: "authProvider", label: "Auth provider", kind: "select", options: ["Local", "OAuth", "SAML"] },
      { key: "dashboards", label: "Dashboards", kind: "number", min: 0, max: 500 },
    ],
    summaryKeys: ["version", "dashboards"],
    capacityRps: 20000,
    metrics: cpuMetrics(40),
  },
  {
    type: "aws.cloudwatch",
    monthlyCostUsd: 15,
    name: "CloudWatch",
    title: "CloudWatch",
    category: "observability",
    provider: "aws",
    icon: Gauge,
    defaults: { retentionDays: 30, detailedMonitoring: false, alarms: 8 },
    properties: [
      { key: "retentionDays", label: "Log retention", kind: "number", unit: "days", min: 1, max: 3650 },
      { key: "detailedMonitoring", label: "Detailed monitoring", kind: "switch" },
      { key: "alarms", label: "Alarms", kind: "number", min: 0, max: 500 },
    ],
    summaryKeys: ["retentionDays", "alarms"],
    capacityRps: 20000,
    metrics: [{ key: "ingest", label: "Ingest", unit: "%", coef: 38 }],
  },
  {
    type: "opensource.opentelemetry",
    monthlyCostUsd: 18,
    name: "OpenTelemetry",
    title: "OpenTelemetry Collector",
    category: "observability",
    provider: "opensource",
    icon: Satellite,
    defaults: { exporters: "otlp, prometheus", samplingPct: 10, replicas: 2 },
    properties: [
      { key: "exporters", label: "Exporters", kind: "text", placeholder: "otlp, prometheus" },
      { key: "samplingPct", label: "Sampling", kind: "number", unit: "%", min: 1, max: 100 },
      { key: "replicas", label: "Replicas", kind: "number", min: 1, max: 20 },
    ],
    summaryKeys: ["replicas", "samplingPct"],
    capacityRps: 25000,
    metrics: cpuMetrics(46),
  },
];

/** PRD §10 — ordem e rótulo das seções da Component Library. */
export const LIBRARY_SECTIONS: { category: Category; label: string }[] = [
  { category: "compute", label: "Compute" },
  { category: "storage", label: "Storage" },
  { category: "database", label: "Database" },
  { category: "cache", label: "Cache" },
  { category: "network", label: "Network" },
  { category: "queue", label: "Messaging" },
  { category: "observability", label: "Observability" },
  { category: "testing", label: "Testing" },
];

const CATALOG_BY_TYPE = new Map(CATALOG.map((item) => [item.type, item]));

export function getCatalogItem(type: string): CatalogItem | undefined {
  return CATALOG_BY_TYPE.get(type);
}

/** Tipo especial do Load Generator (PRD §15). Não vive no catálogo de recursos. */
export const LOAD_GENERATOR_TYPE = "testing.load-generator";
